name: CodexManager
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 6.0
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  CodexManager:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/CodexManager
    resources:
      - path: Sources/CodexManager/Resources
    settings:
      base:
        PRODUCT_NAME: CodexManager
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleName: CodexManager
        INFOPLIST_KEY_CFBundleDisplayName: CodexManager
        INFOPLIST_KEY_LSMinimumSystemVersion: "14.0"
        INFOPLIST_KEY_LSUIElement: YES
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 5
        MARKETING_VERSION: 1.0.7
        DEVELOPMENT_TEAM: KLU8GF65GP
        PRODUCT_BUNDLE_IDENTIFIER: com.nik.mei.codexmanager
  CodexManagerTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Tests/CodexManagerTests
    dependencies:
      - target: CodexManager
schemes:
  CodexManager:
    build:
      targets:
        CodexManager: all
        CodexManagerTests: [test]
    test:
      targets:
        - CodexManagerTests
